hirosystems/stacks-subnets

testnet/stacks-node/src/burnchains/mock_events.rs
testnet/stacks-node/src/burnchains/mod.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/tests/mod.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This PR tests the RPC interface by repurposing one of the old integration tests (the faucet test) as a mock hyperchain test, exercising the RPC interface (importantly, the chain tip selection).

Test: adapt old faucet integration test to a mock hyperchain test

---

.github/actions/bitcoin-int-tests/Dockerfile.stacks-node
.github/workflows/stacks-blockchain.yml
Cargo.lock
src/burnchains/mod.rs
src/chainstate/stacks/boot/contract_tests.rs
testnet/stacks-node/Cargo.toml
testnet/stacks-node/src/burnchains/l1_events.rs
testnet/stacks-node/src/burnchains/mock_events.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/run_loop/l1_observer.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/tests/l1_observer_test.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This contains a handful of changes:
1. Renames the binary output to `hyperchain-node` from `stacks-node`
2. Changes the way the path settings work for the l1_observer_test so that it defaults to running `stacks-node` out of the OS `PATH`.
3. Some fixes to the configurations so that the mockstack tests work again.
4. Changes to the github actions to _hopefully_ execute all of these tests correctly.

HTTP Listener test fixes

---

src/burnchains/burnchain.rs
src/burnchains/events.rs
src/burnchains/indexer.rs
src/util_lib/db.rs
testnet/stacks-node/src/burnchains/db_indexer.rs
testnet/stacks-node/src/burnchains/l1_events.rs
testnet/stacks-node/src/burnchains/mod.rs
testnet/stacks-node/src/burnchains/tests/db_indexer.rs
testnet/stacks-node/src/burnchains/tests/mod.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/run_loop/l1_observer.rs
testnet/stacks-node/src/run_loop/neon.rs
testnet/stacks-node/src/tests/l1_observer_test.rs
testnet/stacks-node/src/tests/mod.rs

This PR contains edits to #50 that might be reviewed as a delta on their own.
Changes:
* `DBBurnchainIndexer` is set as the indexer for `L1Controller`. This can be the production set-up.
* This means that `tests::l1_observer_test::l1_observer_test` is now an end-to-end integration test exercising `DBBurnchainIndexer`.
* `DBBlockDownloader` is implemented by using `serde_json` to serialize the full `NewBlock` to the `headers` table.
* `StacksL1Controller` is modified to print out all the L1 output, and to do so in a yellow font.
- towards #43
Still TBD:
* make use of `first_header_hash`
* unit tests for `sync_with_indexer`
* do we actually have a `bitcoin-tests.yml`?

feat: L1Controller uses DBBurnchainIndexer

---

src/burnchains/burnchain.rs
src/burnchains/test.rs
src/chainstate/coordinator/tests.rs
src/chainstate/stacks/block.rs
src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/mod.rs
src/chainstate/stacks/db/transactions.rs
src/chainstate/stacks/miner.rs
src/clarity_cli.rs
src/net/download.rs
src/net/mod.rs
testnet/stacks-node/src/burnchains/db_indexer.rs
testnet/stacks-node/src/burnchains/l1_events.rs
testnet/stacks-node/src/burnchains/mock_events.rs
testnet/stacks-node/src/burnchains/mod.rs
testnet/stacks-node/src/burnchains/tests/db_indexer.rs
testnet/stacks-node/src/burnchains/tests/mod.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/run_loop/l1_observer.rs
testnet/stacks-node/src/tests/l1_observer_test.rs

This PR should bring the number of warnings after #57 down to 0.
This is basically a mechanical change.
Testing:
* see no errors from `cargo check` or `cargo test` in either base level or `testnet/stacks-node`
* tested with existing tests

chore: Fix rust warnings

---

src/chainstate/burn/db/sortdb.rs
testnet/stacks-node/src/tests/l1_observer_test.rs

Adds `wait_for_next_stacks_block` to wait for the height of the *stacks* tip to increment.
Looks like `l1_integration_test` is passing reliably now.
- fixes #73

fix: Wait for Stacks Blocks in Integration test

---

testnet/stacks-node/src/tests/l1_observer_test.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Towards more reliable and precise tests:
1) Fix a bug in `wait_for_next_stacks_block` where we counted the stacks tip height incorrectly.
2) Start using the `test_observer` in L2 tests, so we can check which L2 blocks actually got produced.
3) Add a new L2 test `l2_simple_contract_calls` to check these above points, as well as exercise the system.
- fixes # 74
Drawback: Still have to wait for "extra" stacks blocks, compared to what one would think, in order to avoid flakes. E.g., we have to wait 2 stacks blocks for 1 transaction to clear, probably so that it can propagate through the mempool. Would be nice to have a "wait for my transaction to hit the mempool" feature.

fix: More test reliability changes

---

src/chainstate/burn/db/sortdb.rs
testnet/stacks-node/src/burnchains/l1_events.rs
testnet/stacks-node/src/burnchains/mock_events.rs
testnet/stacks-node/src/burnchains/mod.rs
testnet/stacks-node/src/burnchains/tests/db_indexer.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/l1_observer_test.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Adds the ability to create a forking integration test.
* Make it so the MockController can make forking paths
* Add `no_contract_calls_forking_integration_test` to exercise the forks
* Leverage #86 
Towards #87, added to `next_block_and_wait` so that it will also wait for a new SortitionDB block. This should remove a category of race condition, in which the next SortitionDB block is not ready after calling `next_block_and_wait`.
- towards #66
- towards #87

feat: add forking to MockNet, and constructs for test synchonization

---

core-contracts/tests/hyperchains/hyperchains_test.ts

Set clarinet version to `0.31.0`.
- fixes #100

fix: use latest clarinet test lib 

---

Cargo.lock
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/l1_observer_test.rs
testnet/stacks-node/src/tests/mod.rs
testnet/stacks-node/src/tests/neon_integrations.rs

This change makes it so that the user can specify `wait_before_first_anchored_block`, which specifies a number of milliseconds to wait, after hearing about a burn block, before starting an anchored block.
This allows the system to make micro-blocks in this time.
- this is towards requests added to #67
- decreases flakiness in some `l1_observer_test` tests by using `wait_for_next_stacks_block` (#87) 
Benefits:
* this is done to create a window of, e.g., "5 minutes", in which micro-blocks are created, so users can get immediate confirmation of the transactions in that time
Drawbacks:
* if the burn block time is less than e.g. "5 minutes", we will miss that burn block
* transactions are treated differently, depending on whether they go into micro-blocks or the main block
An alternative is to …

feat: wait M minutes before starting an anchored block

---

src/chainstate/stacks/miner.rs
src/core/mempool.rs
testnet/stacks-node/src/tests/neon_integrations.rs

Adding a test that makes 3 copies of a transaction in three subsequent micro-blocks in the "wait M minutes" period (#102) before a anchored block.
I made this test to work on #67.
After implementing this test, it seems like the features asked for might already exist without adding code so I'm just adding the test.
- towards #67

test: Interleaving micro-block test

---

contrib/scripts/nft-use-case/withdraw_nft_l1.js

The NFT use case temporarily broke, since PR #142 updated the `withdraw_nft_l1.js` script to correspond with the updated hyperchains contract. However, clarinet currently uses a different version of the hyperchains contract, which led to issues. 
Deploying the new version of the hyperchains contract on the testnet is currently impossible, since the new version uses a Clarity2 function. Thus, we are leaving the old version of the hyperchains contract as the default one launched by Clarinet, and reverting the change in the `withdraw_nft_l1.js` script.

revert withdraw_nft_l1 script

---

core-contracts/contracts/hyperchains.clar
core-contracts/tests/hyperchains/hyperchains_test.ts

<!--
IMPORTANT
Pull requests are ideal for making small changes to this project. However, they are NOT an appropriate venue to introducing non-trivial or breaking changes to the codebase.
Before changes in Stacks 2.1, it was not possible to put a trait inside of an `optional`. Now, it is.
So, this PR refactors the `hyperchains.clar` contract to eliminate redundancy in `withdraw-nft-asset`.
- fixes #165
TBD:
* rename `hyperchains.clar` to `subnets.clar`

feat: Refactor `hyperchains.clar` to use optional traits

---

core-contracts/contracts/subnet.clar

This function is not used anywhere and has similar functionality (but a different return type) as is-miner.

Removes the unused function is-principal-eq.

---

.github/workflows/project-automation.yml

Classic project has been migrated to https://github.com/orgs/hirosystems/projects/24 .
This should address adding new issues to the project.

Update project automation - new project id

---

.github/workflows/ci.yml
src/net/poll.rs

Fix a couple flaky CI tests. The tests fixed are the ones that have been failingin recent PRs that couldn't be explained by problems with the PR itself. Relevant tests are described in linked issue. As far as I can tell, all tests seem to pass now
- fixes #204
This PR may not fix all flaky tests, but it fixes the most common failures, so I'd like to get it merged and close this issue. If any more flaky tests are discovered, we should create a new issue for each test with relevant error logs, rather than trying to address them all in one issue/PR.

fix(ci): Fix some flaky tests

---

src/chainstate/stacks/miner.rs
src/chainstate/stacks/mod.rs
src/net/connection.rs
src/net/http.rs
src/net/mod.rs
src/net/rpc.rs
testnet/stacks-node/src/burnchains/commitment.rs
testnet/stacks-node/src/burnchains/l1_events.rs
testnet/stacks-node/src/burnchains/mock_events.rs
testnet/stacks-node/src/burnchains/mod.rs
testnet/stacks-node/src/config.rs
testnet/stacks-node/src/neon_node.rs
testnet/stacks-node/src/tests/l1_multiparty.rs

Require block proposals to be signed by an approved signer before proceeding to parse and validate the proposal.  Because validating a block proposal is an expensive operation, allowing anyone to submit a proposal would be a potential Denial of Service attack vector.
See corresponding issue for full details.
- fixes #135
- I know I'm going to need to add some integration tests. I'm creating the pull request now in order to get some feedback on the code and some advice on testing
- I chose to hex encode the proposal message before signing it. This allows us to validate the message signature before fully deserializing the JSON. I chose hex encoding over base64 to avoid introducing an extra dependency
- Membership in the set of allowed signers is currently checked using `Vec::contains()`. …

feat: Add sender validation to block proposal RPC

---

core-contracts/contracts/subnet.clar

```
(print {
event: "register-contract",
asset-type: "nft",
l1-contract: (contract-of nft-contract),
l2-contract: l2-contract
})
```

feat: add events for ft/nft registrations

---

Dockerfile

For some reason, the docker image does not work when based on alpine.

fix: use bullseye instead of alpine for docker image

---

.vscode/settings.json

Add a couple lines in `.vscode/settings.json` so that the Deno VSCode extension works correctly

Fix errors in Deno VSCode extension

---

src/chainstate/stacks/boot/subnet.clar

Return the block height of the withdrawal from the `-withdraw?` functions and add it to the print event.

Withdrawal height

---

.gitignore
core-contracts/README.md
core-contracts/contracts/helper/simple-ft-l2.clar
core-contracts/contracts/helper/simple-ft.clar
core-contracts/tests/subnets/subnet_test.ts

Added some failing tests for the `subnet.clar` contract. Some examples include:
- Try to register miner twice
- Try to withdraw using invalid root/leaf/sibling hashes
- Try to withdraw to wrong principal
- Try to overflow token balance 
- fixes #219

Add some more subnet contract tests

---

.github/workflows/ci.yml
.github/workflows/docker-platforms.yml
Dockerfile
Dockerfile.stretch
build-scripts/Dockerfile.linux-arm64
build-scripts/Dockerfile.linux-armv7
build-scripts/Dockerfile.linux-musl-x64
build-scripts/Dockerfile.linux-x64
build-scripts/Dockerfile.macos-arm64
build-scripts/Dockerfile.macos-x64
build-scripts/Dockerfile.windows-x64
src/net/rpc.rs
testnet/stacks-node/src/main.rs

The `/v2/info` endpoint is updated to report "subnet-node" instead of
"stacks-node".

fix: update `server_version`

---

src/burnchains/burnchain.rs
src/burnchains/events.rs
src/burnchains/mod.rs
src/burnchains/test.rs

API endpoints `extended/v1/block` and `extended/v1/block` were empty/zero values for the following variables:
```json
{
"burn_block_time": 0,
"burn_block_time_iso": "",
"parent_burn_block_time": 0,
"parent_burn_block_time_iso": ""
}
```
This was due to failing to parse and store the timestamp from the burnchain block in `StacksSubnetBlock::from_new_block_event()`. This PR fixes this issue so that these variables are now proper Unix and ISO-8601 timestamps:
```json
{
"burn_block_time": 1679512099,
"burn_block_time_iso": "2023-03-22T19:08:19.000Z",
"parent_burn_block_time": 1679512039,
"parent_burn_block_time_iso": "2023-03-22T19:07:19.000Z",
}
```
- fixes #239 
We still report `0` for genesis block. Not sure if that's a problem

fix: Return non-zero value for `burn_block_time` in v1 API

---

src/core/mod.rs

When Epoch 2.1 rules activate on a subnet, the subnet's `net` module will ignore peers with `peer_version`s that have a final byte less than `0x06`.
This was causing our deployed subnet follower to be unable to communicate with the deployed leader.
Once this merges, simply restarting the nodes with this change should address the networking issue.

Fix: peer versions must end in `0x06`

---

src/clarity_vm/withdrawal.rs
testnet/stacks-node/src/tests/l1_observer_test.rs

Rename `withdrawal_id` to `withdrawal-id`, because we should be consistently using kebab-case for Clarity values 
- fixes #245 
I'm not sure if the following lines in `http.rs` should be changed also:
```rust
HttpRequestType::GetWithdrawalStx { .. } => {
"/v2/withdrawal/stx/:block-height/:sender/:withdrawal_id/:amount"
}
HttpRequestType::BlockProposal(..) => PATH_STR_POST_BLOCK_PROPOSAL,
HttpRequestType::GetWithdrawalFt { .. } => {
"/v2/withdrawal/ft/:block-height/:sender/:withdrawal_id/:contract_address/:contract_name/:amount"
}
HttpRequestType::GetWithdrawalNft { .. } => {
"/v2/withdrawal/nft/:block-height/:sender/:withdrawal_id/:contract_address/:contract_name/:id"
}
```
I don't understand this syntax and have no idea what it means

Fix: Rename `withdrawal_id` to `withdrawal-id`

---

core-contracts/contracts/helper/simple-ft-l2-no-deposit.clar
src/chainstate/stacks/db/blocks.rs
testnet/stacks-node/src/tests/l1_observer_test.rs

If a fungible token deposit onto a subnet fails, create a withdrawal transaction to allow the user to withdraw it from the contract
- fixes #146 
There is no attempt here to handle the case of a partial success (for example, a user deposits 50 tokens and only 20 appear on the subnet). This shouldn't happen, and if it does I would think it indicates a problem with the Clarity contract.
Should I move `make_withdrawal_event()` out of blocks.rs and into clarity_vm/withrdawal.rs?
Also including a couple minor fixes, see commit messages for details.

Fix: Refund failed FT deposits

---

src/burnchains/mod.rs
src/net/download.rs
src/net/inv.rs
testnet/stacks-node/src/burnchains/db_indexer.rs
testnet/stacks-node/src/burnchains/mock_events.rs
testnet/stacks-node/src/run_loop/neon.rs

This PR fixes a handful of issues that cropped up while running on testnet.
1. Ignoring L1 blocks before the first block height: this ensures that if a reorg occurs before the first block height, the node doesn't need to backtrack (potentially through blocks it hasn't received data for).
2. The neon run loop needs to increment the "target_burnchain_block", even without PoX reward cycles. To do this, we just use a constant value.
3. On restarting a paired `stacks-node` and `subnet-node`, the `stacks-node` may re-broadcast the last event it broadcasted. In such cases, the `subnet-node` should just drop the duplicate data.
4. The p2p inventory sync needs to send GetBlockInv messages even though the PoX reward cycle sync is broken in subnets (because there's no PoX cycles!)

Fix: handful of resiliency fixes

---

src/chainstate/stacks/mod.rs
src/chainstate/stacks/transaction.rs

The upstream changes for 2.1 added support to pass the Clarity version when deploying a contract. Using this new transaction type is the default from stacks.js, so it makes sense to support this new type in the subnet as well.

fix: support versioned contract transactions

---

.github/workflows/ci.yml

Push to DockerHub on branch commits, but only if we have credentials. This will make it easier to develop using `clarinet integrate`, which by default pulls Subnets from DockerHub
This PR reverts a change I made in #214, but only attempts the push to DockerHub if we have credentials, so we won't get CI failures when working in forked repos

ci: Push to DockerHub on branch commits, but only if we have credentials

---

Cargo.lock
testnet/stacks-node/Cargo.toml

Update `reqwest` dependency and remove OpenSSL support
- fixes a few CVEs found by GitHub's automated scanner
There are a few reasons to prefer Rustls over OpenSSL:
- Avoid security risks associated with using FFI and interfacing with C code
- Simplifies builds (especially cross-compiles) by not requiring external libraries
- Has been formally audited by Cure53 (see [here](https://github.com/rustls/rustls/tree/main/audit))

fix: Update `reqwest` and disable OpenSSL to address CVEs

---

core-contracts/contracts/multi-miner.clar
core-contracts/contracts/subnet.clar
core-contracts/tests/subnets/multiminer_test.ts
core-contracts/tests/subnets/subnet_test.ts
src/chainstate/stacks/miner.rs
testnet/stacks-node/src/burnchains/commitment.rs
testnet/stacks-node/src/burnchains/l1_events.rs
testnet/stacks-node/src/burnchains/mock_events.rs
testnet/stacks-node/src/burnchains/mod.rs
testnet/stacks-node/src/neon_node.rs

The event generated by a `commit-block` (on the L1) now includes the
block height for the block that is being committed, in the
`block-height` key of the event tuple. The target burnchain block height
now uses the key `target-burn-block-height`. This is useful for
debugging, making it easy to match the L1 transactions with the L2
blocks. Note that this field is not checked in the tests since it is
purely for convenience and could be left out of some implementations.

feat: add block height to `commit-block` event

---

.github/workflows/ci.yml

Fixes the `docker push` step of CI by explicitly checking if a string is empty using `!=`, rather than relying on an implicit cast
This fixes an issue introduced by #258. If you check [here](https://github.com/hirosystems/stacks-subnets/actions/runs/4735274334), when I made these changes they worked fine. I'm not sure what changed since them to make it fail now.

ci: Add explicit `!= ''` comparisons to test if strings are non-empty

---

docs/getting-started.md
docs/overview.md

Updates to subnets documentation, specifically the Getting Started guide and Overview page, the result of feedback.

Changes to subnets Getting Started and Overview guides

---

docs/getting-started.md
docs/overview.md

Penultimate changes to Getting Started guide before preview announcement to Discord on Friday. Changes pertain mostly to docker tags, also some additional clarifying language. 
PR is not complete, needs resolution of `$ node ./verify.js 2` bug which returns `none` instead of expected account, one of the last steps in the guide.

Walkthrough guide edits

---

core-contracts/contracts/multi-miner.clar
core-contracts/contracts/subnet.clar
testnet/stacks-node/src/burnchains/l1_events.rs
testnet/stacks-node/src/burnchains/mod.rs

Properly deserialize response from call to read-only function `get-version` in `subnet.clar`
- fixes #276
This is somewhat messy, and contains some `unwrap()`s and `panic!()`s when things don't go as expected (although I don't really expect them to ever be triggered). We are trying to get this out ASAP, so I'll clean up later.

fix: Should fix failures reading subnet contract version

---

core-contracts/contracts/subnet.clar

This change is already in the deployed contract, but I forgot to add it in #275.

fix: use latest version of `subnet-traits` contract

---

src/core/mod.rs
testnet/stacks-node/src/config.rs

Previously, the chain ID from the config file was ignored:
```toml
[node]
chain_id = 0x55005500
```
This now uses that chain ID, and also sets the default to this `0x55005500` to avoid accidentally matching the L1 chain ID by default.

fix: use chain ID from config file

---

core-contracts/Clarinet.toml
core-contracts/contracts/helper/simple-ft.clar
core-contracts/contracts/helper/simple-nft.clar
core-contracts/tests/subnets/multiminer_test.ts
core-contracts/tests/subnets/subnet_test.ts

CI was failing because of the addition of subnet contract versioning. This PR adds the subnet contract version in Clarinet tests
- fixes #283 
This required changing quite a bit of code. If anyone can think of a better way to do this I'll cancel the PR

ci: Update subnet contract version in Clarinet tests

---

src/net/inv.rs

I think this change will solve the follower synchronization issues.
Tested locally with a subnet follower and it successfully caught up to the subnet chain tip.

Fix: mock pox inventory sync calculation requires +1

---

.github/workflows/ci.yml

This now logs in, builds, and pushes the Docker image in the main repository: https://github.com/hirosystems/stacks-subnets/actions/runs/5282021630/jobs/9556390408
- Fix checking of `DOCKER_PUSH` env variable so that Docker login step is not skipped
- Fix Docker tags

ci: Fix Docker login step

---

src/burnchains/burnchain.rs
src/chainstate/burn/db/processing.rs

This PR sorts accepted L1 operations by their txids so that `ops_hash` and `consensus_hash` are consistent between nodes. This also makes op ordering in the block_ops tables consistent.
It is necessary to sort by txid because the current version of the subnet codebase _does not_ track a "vtxindex"-like field for the Stacks L1 operations.

Fix: sort L1 accepted_ops by L1 txid

---

.github/workflows/ci.yml

Add `set -o pipefail` to CI job `compute-layer-1-tests` so proper exit status is reported
- fixes #309

Fix exit status for CI job `compute-layer-1-tests` 

---

src/chainstate/stacks/db/blocks.rs
src/chainstate/stacks/db/mod.rs
src/core/mempool.rs

Retry certain failed transactions against latest microblocks (`unconfirmed_state`)
- fixes #299
Still need to write tests to confirm this behaves as expected. Due to time constraints, I'm going to merge this and create a new issue for the tests.

feat: Retry certain failed transactions against latest microblocks

---

Dockerfile
src/chainstate/stacks/db/mod.rs
src/net/http.rs
src/net/rpc.rs

This PR contains the following changes:
- Change all API endpoints to use latest microblock state by default
- Add option to force anchored block use by adding `anchored` to the HTTP query
- Some minor style changes
- fixes #298
This PR has a wider scope than the associated issue, as it affects all API endpoints which can accept a `tip=<string>` parameter. I'm not sure if this is desirable.
Treating microblocks as confirmed creates some inconsistency in how microblocks are reported by the API:
- Although now treated as confirmed, the latest microblock txs aren't returned by the API when `/extended/v1/tx/` is queried
- When querying the `/extended/v1/tx/{txid}` endpoint before the tx is included in an anchor block, it will have `"tx_status": "pending"` set
Since API requests now default to …

feat: API now responds with state from latest microblocks by default

---

src/burnchains/mod.rs
testnet/stacks-node/src/burnchains/db_indexer.rs
testnet/stacks-node/src/neon_node.rs

This uses @kantai's suggestion to avoid the race condition detected when deciding if a reorg happened.

Fix reorg handling
